
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
  application:
    name: spring-hello-world
server:
  port: 8666
management:
  endpoints:
    web:
      exposure:
        include: '*'
